# Generated by Django 3.1.4 on 2020-12-07 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100, null=True)),
                ('category_content', models.CharField(max_length=100, null=True)),
                ('memo', models.TextField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'processes',
            },
        ),
        migrations.CreateModel(
            name='ContractProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('issue_date', models.DateField(null=True)),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.process')),
                ('target_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
            ],
            options={
                'db_table': 'contract_processes',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='process',
            field=models.ManyToManyField(through='contract.ContractProcess', to='contract.Process'),
        ),
        migrations.AddField(
            model_name='contract',
            name='representative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.representative'),
        ),
    ]
