# Generated by Django 3.1.4 on 2020-12-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='content',
        ),
        migrations.AddField(
            model_name='contract',
            name='category_content',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
