# Generated by Django 3.1.4 on 2020-12-07 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100, null=True)),
                ('category_content', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.RemoveField(
            model_name='contract',
            name='category',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='category_content',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='subcategory',
        ),
        migrations.CreateModel(
            name='ContractCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.category')),
                ('target_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
            ],
            options={
                'db_table': 'contract_categories',
            },
        ),
    ]
