# Generated by Django 3.1.4 on 2020-12-03 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201203_0823'),
        ('contract', '0002_auto_20201203_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='representative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.representative'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
