# Generated by Django 3.1.4 on 2020-12-03 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.group'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='phone_num',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
